/**
 * FeatureExtractor.java
 */
package artiano.statistics.extractor;

/**
 * <p>Description:</p>
 * @author Nano.Michael
 * @version 1.0.0
 * @date 2013-8-22
 * @author (latest modification by Nano.Michael)
 * @since 1.0.0
 */
public interface FeatureExtractor {
	/**
	 * load extractor from file
	 * @param filename - specified file
	 */
	public void load(String filename);
	/**
	 * save extractor to file
	 * @param filename - specified file
	 */
	public void save(String filename);
	/**
	 * train an extractor
	 */
	public void train();
	/**
	 * extract features from sample
	 */
	public void extract(double[] sample);
	
	/**
	 * get model from the extractor
	 * @return - the model generated by extractor
	 */
	public double[][] getModel();
}
