/**
 * FeatureExtractor.java
 */
package artiano.statistics.extractor;

import artiano.core.operation.Preservable;
import artiano.core.structure.Matrix;

/**
 * <p>Description:</p>
 * @author Nano.Michael
 * @version 1.0.0
 * @date 2013-8-22
 * @author (latest modification by Nano.Michael)
 * @since 1.0.0
 */
public abstract class FeatureExtractor extends Preservable{
	
	private static final long serialVersionUID = 1L;

	/**
	 * extract features from sample
	 * @param sample - input sample
	 * @return - features of the sample
	 */
	public abstract Matrix extract(Matrix sample);
	
	/**
	 * reconstruct the matrix according to the feature extracted
	 * @param feature - the feature extracted
	 * @return - the matrix reconstructed
	 */
	public abstract Matrix reconstruct(Matrix feature);
	
	/**
	 * get model from the extractor
	 * @return - the model generated by extractor
	 */
	public abstract Matrix getModel();
}
